:bulb: Create README.md
Peralban/Zappy pull request #52
Opened 2024-06-10 08:20 UTC by aimericdrk

2024-06-10 08:46 UTC, Peralban requested changes

2024-06-10 08:46 UTC, Peralban commented on README.md
> +```sh
no sh because here time and for are recognized like command and not word.

2024-06-10 09:57 UTC, landryarki requested changes

2024-06-11 13:10 UTC, Antoinegtir reviewed
Please a description of the PR

2024-06-11 13:59 UTC, Antoinegtir approved these changes

2024-06-11 14:02 UTC, Neiluge approved these changes

2024-06-12 08:22 UTC, merged